apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  labels:
    name: bash-test
spec:
  restartPolicy: Always
  containers:
    - image: bashell/alpine-bash
      name: bash
      volumeMounts:
      - mountPath: "/data"
        name: vol
      command: [ "sleep", "1000000" ]
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: storage-pvc
